package com.siyi.train.business.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class DailyTrainStation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.id
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.date
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.train_code
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private String trainCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.index
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private Integer index;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.name
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.name_pinyin
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private String namePinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.in_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private Date inTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.out_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private Date outTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.stop_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private Date stopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.km
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private BigDecimal km;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.create_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_train_station.update_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.id
     *
     * @return the value of daily_train_station.id
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.id
     *
     * @param id the value for daily_train_station.id
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.date
     *
     * @return the value of daily_train_station.date
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.date
     *
     * @param date the value for daily_train_station.date
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.train_code
     *
     * @return the value of daily_train_station.train_code
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.train_code
     *
     * @param trainCode the value for daily_train_station.train_code
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.index
     *
     * @return the value of daily_train_station.index
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.index
     *
     * @param index the value for daily_train_station.index
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.name
     *
     * @return the value of daily_train_station.name
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.name
     *
     * @param name the value for daily_train_station.name
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.name_pinyin
     *
     * @return the value of daily_train_station.name_pinyin
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public String getNamePinyin() {
        return namePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.name_pinyin
     *
     * @param namePinyin the value for daily_train_station.name_pinyin
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setNamePinyin(String namePinyin) {
        this.namePinyin = namePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.in_time
     *
     * @return the value of daily_train_station.in_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.in_time
     *
     * @param inTime the value for daily_train_station.in_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.out_time
     *
     * @return the value of daily_train_station.out_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.out_time
     *
     * @param outTime the value for daily_train_station.out_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.stop_time
     *
     * @return the value of daily_train_station.stop_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public Date getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.stop_time
     *
     * @param stopTime the value for daily_train_station.stop_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setStopTime(Date stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.km
     *
     * @return the value of daily_train_station.km
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public BigDecimal getKm() {
        return km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.km
     *
     * @param km the value for daily_train_station.km
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setKm(BigDecimal km) {
        this.km = km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.create_time
     *
     * @return the value of daily_train_station.create_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.create_time
     *
     * @param createTime the value for daily_train_station.create_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_train_station.update_time
     *
     * @return the value of daily_train_station.update_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_train_station.update_time
     *
     * @param updateTime the value for daily_train_station.update_time
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", date=").append(date);
        sb.append(", trainCode=").append(trainCode);
        sb.append(", index=").append(index);
        sb.append(", name=").append(name);
        sb.append(", namePinyin=").append(namePinyin);
        sb.append(", inTime=").append(inTime);
        sb.append(", outTime=").append(outTime);
        sb.append(", stopTime=").append(stopTime);
        sb.append(", km=").append(km);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}