package com.siyi.train.business.pojo;

import java.util.Date;

public class SkToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_token.id
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_token.date
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_token.train_code
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    private String trainCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_token.count
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_token.create_time
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_token.update_time
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_token.id
     *
     * @return the value of sk_token.id
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_token.id
     *
     * @param id the value for sk_token.id
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_token.date
     *
     * @return the value of sk_token.date
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_token.date
     *
     * @param date the value for sk_token.date
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_token.train_code
     *
     * @return the value of sk_token.train_code
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_token.train_code
     *
     * @param trainCode the value for sk_token.train_code
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_token.count
     *
     * @return the value of sk_token.count
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_token.count
     *
     * @param count the value for sk_token.count
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_token.create_time
     *
     * @return the value of sk_token.create_time
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_token.create_time
     *
     * @param createTime the value for sk_token.create_time
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_token.update_time
     *
     * @return the value of sk_token.update_time
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_token.update_time
     *
     * @param updateTime the value for sk_token.update_time
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", date=").append(date);
        sb.append(", trainCode=").append(trainCode);
        sb.append(", count=").append(count);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}