package com.siyi.train.business.pojo;

import java.util.Date;

public class TrainSeat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_seat.id
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_seat.train_code
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    private String trainCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_seat.carriage_index
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    private Integer carriageIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_seat.row
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    private String row;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_seat.col
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    private String col;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_seat.seat_type
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    private String seatType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_seat.carriage_seat_index
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    private Integer carriageSeatIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_seat.create_time
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_seat.update_time
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.id
     *
     * @return the value of train_seat.id
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.id
     *
     * @param id the value for train_seat.id
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.train_code
     *
     * @return the value of train_seat.train_code
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.train_code
     *
     * @param trainCode the value for train_seat.train_code
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.carriage_index
     *
     * @return the value of train_seat.carriage_index
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public Integer getCarriageIndex() {
        return carriageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.carriage_index
     *
     * @param carriageIndex the value for train_seat.carriage_index
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public void setCarriageIndex(Integer carriageIndex) {
        this.carriageIndex = carriageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.row
     *
     * @return the value of train_seat.row
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public String getRow() {
        return row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.row
     *
     * @param row the value for train_seat.row
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public void setRow(String row) {
        this.row = row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.col
     *
     * @return the value of train_seat.col
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public String getCol() {
        return col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.col
     *
     * @param col the value for train_seat.col
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public void setCol(String col) {
        this.col = col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.seat_type
     *
     * @return the value of train_seat.seat_type
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public String getSeatType() {
        return seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.seat_type
     *
     * @param seatType the value for train_seat.seat_type
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public void setSeatType(String seatType) {
        this.seatType = seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.carriage_seat_index
     *
     * @return the value of train_seat.carriage_seat_index
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public Integer getCarriageSeatIndex() {
        return carriageSeatIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.carriage_seat_index
     *
     * @param carriageSeatIndex the value for train_seat.carriage_seat_index
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public void setCarriageSeatIndex(Integer carriageSeatIndex) {
        this.carriageSeatIndex = carriageSeatIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.create_time
     *
     * @return the value of train_seat.create_time
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.create_time
     *
     * @param createTime the value for train_seat.create_time
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_seat.update_time
     *
     * @return the value of train_seat.update_time
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_seat.update_time
     *
     * @param updateTime the value for train_seat.update_time
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", trainCode=").append(trainCode);
        sb.append(", carriageIndex=").append(carriageIndex);
        sb.append(", row=").append(row);
        sb.append(", col=").append(col);
        sb.append(", seatType=").append(seatType);
        sb.append(", carriageSeatIndex=").append(carriageSeatIndex);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}