package com.siyi.train.business.pojo;

import java.util.Date;

public class Train {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.id
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.code
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.type
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.start
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    private String start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.start_pinyin
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    private String startPinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.start_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.end
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    private String end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.end_pinyin
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    private String endPinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.end_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.create_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.update_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.id
     *
     * @return the value of train.id
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.id
     *
     * @param id the value for train.id
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.code
     *
     * @return the value of train.code
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.code
     *
     * @param code the value for train.code
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.type
     *
     * @return the value of train.type
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.type
     *
     * @param type the value for train.type
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.start
     *
     * @return the value of train.start
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.start
     *
     * @param start the value for train.start
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public void setStart(String start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.start_pinyin
     *
     * @return the value of train.start_pinyin
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public String getStartPinyin() {
        return startPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.start_pinyin
     *
     * @param startPinyin the value for train.start_pinyin
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public void setStartPinyin(String startPinyin) {
        this.startPinyin = startPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.start_time
     *
     * @return the value of train.start_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.start_time
     *
     * @param startTime the value for train.start_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.end
     *
     * @return the value of train.end
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.end
     *
     * @param end the value for train.end
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public void setEnd(String end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.end_pinyin
     *
     * @return the value of train.end_pinyin
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public String getEndPinyin() {
        return endPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.end_pinyin
     *
     * @param endPinyin the value for train.end_pinyin
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public void setEndPinyin(String endPinyin) {
        this.endPinyin = endPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.end_time
     *
     * @return the value of train.end_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.end_time
     *
     * @param endTime the value for train.end_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.create_time
     *
     * @return the value of train.create_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.create_time
     *
     * @param createTime the value for train.create_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.update_time
     *
     * @return the value of train.update_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.update_time
     *
     * @param updateTime the value for train.update_time
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated Fri Sep 08 17:47:48 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", type=").append(type);
        sb.append(", start=").append(start);
        sb.append(", startPinyin=").append(startPinyin);
        sb.append(", startTime=").append(startTime);
        sb.append(", end=").append(end);
        sb.append(", endPinyin=").append(endPinyin);
        sb.append(", endTime=").append(endTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}