package com.siyi.train.business.pojo;

import java.util.Date;

public class TrainCarriage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_carriage.id
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_carriage.train_code
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    private String trainCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_carriage.index
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    private Integer index;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_carriage.seat_type
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    private String seatType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_carriage.seat_count
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    private Integer seatCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_carriage.row_count
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    private Integer rowCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_carriage.col_count
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    private Integer colCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_carriage.create_time
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_carriage.update_time
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_carriage.id
     *
     * @return the value of train_carriage.id
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_carriage.id
     *
     * @param id the value for train_carriage.id
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_carriage.train_code
     *
     * @return the value of train_carriage.train_code
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_carriage.train_code
     *
     * @param trainCode the value for train_carriage.train_code
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_carriage.index
     *
     * @return the value of train_carriage.index
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_carriage.index
     *
     * @param index the value for train_carriage.index
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_carriage.seat_type
     *
     * @return the value of train_carriage.seat_type
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public String getSeatType() {
        return seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_carriage.seat_type
     *
     * @param seatType the value for train_carriage.seat_type
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public void setSeatType(String seatType) {
        this.seatType = seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_carriage.seat_count
     *
     * @return the value of train_carriage.seat_count
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public Integer getSeatCount() {
        return seatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_carriage.seat_count
     *
     * @param seatCount the value for train_carriage.seat_count
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public void setSeatCount(Integer seatCount) {
        this.seatCount = seatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_carriage.row_count
     *
     * @return the value of train_carriage.row_count
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public Integer getRowCount() {
        return rowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_carriage.row_count
     *
     * @param rowCount the value for train_carriage.row_count
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public void setRowCount(Integer rowCount) {
        this.rowCount = rowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_carriage.col_count
     *
     * @return the value of train_carriage.col_count
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public Integer getColCount() {
        return colCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_carriage.col_count
     *
     * @param colCount the value for train_carriage.col_count
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public void setColCount(Integer colCount) {
        this.colCount = colCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_carriage.create_time
     *
     * @return the value of train_carriage.create_time
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_carriage.create_time
     *
     * @param createTime the value for train_carriage.create_time
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_carriage.update_time
     *
     * @return the value of train_carriage.update_time
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_carriage.update_time
     *
     * @param updateTime the value for train_carriage.update_time
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", trainCode=").append(trainCode);
        sb.append(", index=").append(index);
        sb.append(", seatType=").append(seatType);
        sb.append(", seatCount=").append(seatCount);
        sb.append(", rowCount=").append(rowCount);
        sb.append(", colCount=").append(colCount);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}