package com.siyi.train.business.mapper;

import com.siyi.train.business.pojo.ConfirmOrder;
import com.siyi.train.business.pojo.ConfirmOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfirmOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    long countByExample(ConfirmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    int deleteByExample(ConfirmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    int insert(ConfirmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    int insertSelective(ConfirmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    List<ConfirmOrder> selectByExampleWithBLOBs(ConfirmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    List<ConfirmOrder> selectByExample(ConfirmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    ConfirmOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    int updateByExampleSelective(@Param("record") ConfirmOrder record, @Param("example") ConfirmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") ConfirmOrder record, @Param("example") ConfirmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    int updateByExample(@Param("record") ConfirmOrder record, @Param("example") ConfirmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    int updateByPrimaryKeySelective(ConfirmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(ConfirmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_order
     *
     * @mbg.generated Tue Sep 19 17:41:13 CST 2023
     */
    int updateByPrimaryKey(ConfirmOrder record);
}