package com.siyi.train.business.mapper;

import com.siyi.train.business.pojo.DailyTrainTicket;
import com.siyi.train.business.pojo.DailyTrainTicketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DailyTrainTicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_ticket
     *
     * @mbg.generated Fri Sep 15 17:31:07 CST 2023
     */
    long countByExample(DailyTrainTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_ticket
     *
     * @mbg.generated Fri Sep 15 17:31:07 CST 2023
     */
    int deleteByExample(DailyTrainTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_ticket
     *
     * @mbg.generated Fri Sep 15 17:31:07 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_ticket
     *
     * @mbg.generated Fri Sep 15 17:31:07 CST 2023
     */
    int insert(DailyTrainTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_ticket
     *
     * @mbg.generated Fri Sep 15 17:31:07 CST 2023
     */
    int insertSelective(DailyTrainTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_ticket
     *
     * @mbg.generated Fri Sep 15 17:31:07 CST 2023
     */
    List<DailyTrainTicket> selectByExample(DailyTrainTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_ticket
     *
     * @mbg.generated Fri Sep 15 17:31:07 CST 2023
     */
    DailyTrainTicket selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_ticket
     *
     * @mbg.generated Fri Sep 15 17:31:07 CST 2023
     */
    int updateByExampleSelective(@Param("record") DailyTrainTicket record, @Param("example") DailyTrainTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_ticket
     *
     * @mbg.generated Fri Sep 15 17:31:07 CST 2023
     */
    int updateByExample(@Param("record") DailyTrainTicket record, @Param("example") DailyTrainTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_ticket
     *
     * @mbg.generated Fri Sep 15 17:31:07 CST 2023
     */
    int updateByPrimaryKeySelective(DailyTrainTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_ticket
     *
     * @mbg.generated Fri Sep 15 17:31:07 CST 2023
     */
    int updateByPrimaryKey(DailyTrainTicket record);
}