package com.siyi.train.business.mapper;

import com.siyi.train.business.pojo.DailyTrainSeat;
import com.siyi.train.business.pojo.DailyTrainSeatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DailyTrainSeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_seat
     *
     * @mbg.generated Wed Sep 13 17:50:01 CST 2023
     */
    long countByExample(DailyTrainSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_seat
     *
     * @mbg.generated Wed Sep 13 17:50:01 CST 2023
     */
    int deleteByExample(DailyTrainSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_seat
     *
     * @mbg.generated Wed Sep 13 17:50:01 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_seat
     *
     * @mbg.generated Wed Sep 13 17:50:01 CST 2023
     */
    int insert(DailyTrainSeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_seat
     *
     * @mbg.generated Wed Sep 13 17:50:01 CST 2023
     */
    int insertSelective(DailyTrainSeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_seat
     *
     * @mbg.generated Wed Sep 13 17:50:01 CST 2023
     */
    List<DailyTrainSeat> selectByExample(DailyTrainSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_seat
     *
     * @mbg.generated Wed Sep 13 17:50:01 CST 2023
     */
    DailyTrainSeat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_seat
     *
     * @mbg.generated Wed Sep 13 17:50:01 CST 2023
     */
    int updateByExampleSelective(@Param("record") DailyTrainSeat record, @Param("example") DailyTrainSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_seat
     *
     * @mbg.generated Wed Sep 13 17:50:01 CST 2023
     */
    int updateByExample(@Param("record") DailyTrainSeat record, @Param("example") DailyTrainSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_seat
     *
     * @mbg.generated Wed Sep 13 17:50:01 CST 2023
     */
    int updateByPrimaryKeySelective(DailyTrainSeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_seat
     *
     * @mbg.generated Wed Sep 13 17:50:01 CST 2023
     */
    int updateByPrimaryKey(DailyTrainSeat record);
}