package com.siyi.train.business.mapper;

import com.siyi.train.business.pojo.DailyTrainCarriage;
import com.siyi.train.business.pojo.DailyTrainCarriageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DailyTrainCarriageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_carriage
     *
     * @mbg.generated Wed Sep 13 17:18:24 CST 2023
     */
    long countByExample(DailyTrainCarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_carriage
     *
     * @mbg.generated Wed Sep 13 17:18:24 CST 2023
     */
    int deleteByExample(DailyTrainCarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_carriage
     *
     * @mbg.generated Wed Sep 13 17:18:24 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_carriage
     *
     * @mbg.generated Wed Sep 13 17:18:24 CST 2023
     */
    int insert(DailyTrainCarriage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_carriage
     *
     * @mbg.generated Wed Sep 13 17:18:24 CST 2023
     */
    int insertSelective(DailyTrainCarriage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_carriage
     *
     * @mbg.generated Wed Sep 13 17:18:24 CST 2023
     */
    List<DailyTrainCarriage> selectByExample(DailyTrainCarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_carriage
     *
     * @mbg.generated Wed Sep 13 17:18:24 CST 2023
     */
    DailyTrainCarriage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_carriage
     *
     * @mbg.generated Wed Sep 13 17:18:24 CST 2023
     */
    int updateByExampleSelective(@Param("record") DailyTrainCarriage record, @Param("example") DailyTrainCarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_carriage
     *
     * @mbg.generated Wed Sep 13 17:18:24 CST 2023
     */
    int updateByExample(@Param("record") DailyTrainCarriage record, @Param("example") DailyTrainCarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_carriage
     *
     * @mbg.generated Wed Sep 13 17:18:24 CST 2023
     */
    int updateByPrimaryKeySelective(DailyTrainCarriage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_carriage
     *
     * @mbg.generated Wed Sep 13 17:18:24 CST 2023
     */
    int updateByPrimaryKey(DailyTrainCarriage record);
}