package com.siyi.train.business.mapper;

import com.siyi.train.business.pojo.DailyTrain;
import com.siyi.train.business.pojo.DailyTrainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DailyTrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train
     *
     * @mbg.generated Wed Sep 13 16:10:28 CST 2023
     */
    long countByExample(DailyTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train
     *
     * @mbg.generated Wed Sep 13 16:10:28 CST 2023
     */
    int deleteByExample(DailyTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train
     *
     * @mbg.generated Wed Sep 13 16:10:28 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train
     *
     * @mbg.generated Wed Sep 13 16:10:28 CST 2023
     */
    int insert(DailyTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train
     *
     * @mbg.generated Wed Sep 13 16:10:28 CST 2023
     */
    int insertSelective(DailyTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train
     *
     * @mbg.generated Wed Sep 13 16:10:28 CST 2023
     */
    List<DailyTrain> selectByExample(DailyTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train
     *
     * @mbg.generated Wed Sep 13 16:10:28 CST 2023
     */
    DailyTrain selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train
     *
     * @mbg.generated Wed Sep 13 16:10:28 CST 2023
     */
    int updateByExampleSelective(@Param("record") DailyTrain record, @Param("example") DailyTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train
     *
     * @mbg.generated Wed Sep 13 16:10:28 CST 2023
     */
    int updateByExample(@Param("record") DailyTrain record, @Param("example") DailyTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train
     *
     * @mbg.generated Wed Sep 13 16:10:28 CST 2023
     */
    int updateByPrimaryKeySelective(DailyTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train
     *
     * @mbg.generated Wed Sep 13 16:10:28 CST 2023
     */
    int updateByPrimaryKey(DailyTrain record);
}