package com.siyi.train.business.mapper;

import com.siyi.train.business.pojo.DailyTrainStation;
import com.siyi.train.business.pojo.DailyTrainStationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DailyTrainStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    long countByExample(DailyTrainStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    int deleteByExample(DailyTrainStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    int insert(DailyTrainStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    int insertSelective(DailyTrainStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    List<DailyTrainStation> selectByExample(DailyTrainStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    DailyTrainStation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    int updateByExampleSelective(@Param("record") DailyTrainStation record, @Param("example") DailyTrainStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    int updateByExample(@Param("record") DailyTrainStation record, @Param("example") DailyTrainStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    int updateByPrimaryKeySelective(DailyTrainStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_train_station
     *
     * @mbg.generated Wed Sep 13 17:04:31 CST 2023
     */
    int updateByPrimaryKey(DailyTrainStation record);
}