package com.siyi.train.business.mapper;

import com.siyi.train.business.pojo.SkToken;
import com.siyi.train.business.pojo.SkTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    long countByExample(SkTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    int deleteByExample(SkTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    int insert(SkToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    int insertSelective(SkToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    List<SkToken> selectByExample(SkTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    SkToken selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    int updateByExampleSelective(@Param("record") SkToken record, @Param("example") SkTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    int updateByExample(@Param("record") SkToken record, @Param("example") SkTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    int updateByPrimaryKeySelective(SkToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_token
     *
     * @mbg.generated Mon Oct 16 18:09:51 CST 2023
     */
    int updateByPrimaryKey(SkToken record);
}