package com.siyi.train.business.mapper;

import com.siyi.train.business.pojo.TrainSeat;
import com.siyi.train.business.pojo.TrainSeatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrainSeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    long countByExample(TrainSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    int deleteByExample(TrainSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    int insert(TrainSeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    int insertSelective(TrainSeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    List<TrainSeat> selectByExample(TrainSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    TrainSeat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    int updateByExampleSelective(@Param("record") TrainSeat record, @Param("example") TrainSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    int updateByExample(@Param("record") TrainSeat record, @Param("example") TrainSeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    int updateByPrimaryKeySelective(TrainSeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_seat
     *
     * @mbg.generated Mon Sep 11 16:59:19 CST 2023
     */
    int updateByPrimaryKey(TrainSeat record);
}