package com.siyi.train.business.mapper;

import com.siyi.train.business.pojo.TrainCarriage;
import com.siyi.train.business.pojo.TrainCarriageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrainCarriageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    long countByExample(TrainCarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    int deleteByExample(TrainCarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    int insert(TrainCarriage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    int insertSelective(TrainCarriage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    List<TrainCarriage> selectByExample(TrainCarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    TrainCarriage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    int updateByExampleSelective(@Param("record") TrainCarriage record, @Param("example") TrainCarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    int updateByExample(@Param("record") TrainCarriage record, @Param("example") TrainCarriageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    int updateByPrimaryKeySelective(TrainCarriage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_carriage
     *
     * @mbg.generated Mon Sep 11 16:47:34 CST 2023
     */
    int updateByPrimaryKey(TrainCarriage record);
}