package com.siyi.train.business.mapper;

import com.siyi.train.business.pojo.TrainStation;
import com.siyi.train.business.pojo.TrainStationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrainStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_station
     *
     * @mbg.generated Mon Sep 11 14:47:01 CST 2023
     */
    long countByExample(TrainStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_station
     *
     * @mbg.generated Mon Sep 11 14:47:01 CST 2023
     */
    int deleteByExample(TrainStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_station
     *
     * @mbg.generated Mon Sep 11 14:47:01 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_station
     *
     * @mbg.generated Mon Sep 11 14:47:01 CST 2023
     */
    int insert(TrainStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_station
     *
     * @mbg.generated Mon Sep 11 14:47:01 CST 2023
     */
    int insertSelective(TrainStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_station
     *
     * @mbg.generated Mon Sep 11 14:47:01 CST 2023
     */
    List<TrainStation> selectByExample(TrainStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_station
     *
     * @mbg.generated Mon Sep 11 14:47:01 CST 2023
     */
    TrainStation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_station
     *
     * @mbg.generated Mon Sep 11 14:47:01 CST 2023
     */
    int updateByExampleSelective(@Param("record") TrainStation record, @Param("example") TrainStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_station
     *
     * @mbg.generated Mon Sep 11 14:47:01 CST 2023
     */
    int updateByExample(@Param("record") TrainStation record, @Param("example") TrainStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_station
     *
     * @mbg.generated Mon Sep 11 14:47:01 CST 2023
     */
    int updateByPrimaryKeySelective(TrainStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_station
     *
     * @mbg.generated Mon Sep 11 14:47:01 CST 2023
     */
    int updateByPrimaryKey(TrainStation record);
}