package com.siyi.train.member.pojo;

import java.util.Date;

public class Passenger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.id
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.member_id
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.name
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.id_card
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.type
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.create_time
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.update_time
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.id
     *
     * @return the value of passenger.id
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.id
     *
     * @param id the value for passenger.id
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.member_id
     *
     * @return the value of passenger.member_id
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.member_id
     *
     * @param memberId the value for passenger.member_id
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.name
     *
     * @return the value of passenger.name
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.name
     *
     * @param name the value for passenger.name
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.id_card
     *
     * @return the value of passenger.id_card
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.id_card
     *
     * @param idCard the value for passenger.id_card
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.type
     *
     * @return the value of passenger.type
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.type
     *
     * @param type the value for passenger.type
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.create_time
     *
     * @return the value of passenger.create_time
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.create_time
     *
     * @param createTime the value for passenger.create_time
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.update_time
     *
     * @return the value of passenger.update_time
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.update_time
     *
     * @param updateTime the value for passenger.update_time
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated Fri Aug 18 17:36:00 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", name=").append(name);
        sb.append(", idCard=").append(idCard);
        sb.append(", type=").append(type);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}