package com.siyi.train.member.pojo;

import java.util.Date;

public class Ticket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.id
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.member_id
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.passenger_id
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private Long passengerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.passenger_name
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private String passengerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.train_date
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private Date trainDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.train_code
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private String trainCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.carriage_index
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private Integer carriageIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.seat_row
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private String seatRow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.seat_col
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private String seatCol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.start_station
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private String startStation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.start_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.end_station
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private String endStation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.end_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.seat_type
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private String seatType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.create_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.update_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.id
     *
     * @return the value of ticket.id
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.id
     *
     * @param id the value for ticket.id
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.member_id
     *
     * @return the value of ticket.member_id
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.member_id
     *
     * @param memberId the value for ticket.member_id
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.passenger_id
     *
     * @return the value of ticket.passenger_id
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public Long getPassengerId() {
        return passengerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.passenger_id
     *
     * @param passengerId the value for ticket.passenger_id
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setPassengerId(Long passengerId) {
        this.passengerId = passengerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.passenger_name
     *
     * @return the value of ticket.passenger_name
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public String getPassengerName() {
        return passengerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.passenger_name
     *
     * @param passengerName the value for ticket.passenger_name
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.train_date
     *
     * @return the value of ticket.train_date
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public Date getTrainDate() {
        return trainDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.train_date
     *
     * @param trainDate the value for ticket.train_date
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setTrainDate(Date trainDate) {
        this.trainDate = trainDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.train_code
     *
     * @return the value of ticket.train_code
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.train_code
     *
     * @param trainCode the value for ticket.train_code
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.carriage_index
     *
     * @return the value of ticket.carriage_index
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public Integer getCarriageIndex() {
        return carriageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.carriage_index
     *
     * @param carriageIndex the value for ticket.carriage_index
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setCarriageIndex(Integer carriageIndex) {
        this.carriageIndex = carriageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.seat_row
     *
     * @return the value of ticket.seat_row
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public String getSeatRow() {
        return seatRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.seat_row
     *
     * @param seatRow the value for ticket.seat_row
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setSeatRow(String seatRow) {
        this.seatRow = seatRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.seat_col
     *
     * @return the value of ticket.seat_col
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public String getSeatCol() {
        return seatCol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.seat_col
     *
     * @param seatCol the value for ticket.seat_col
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setSeatCol(String seatCol) {
        this.seatCol = seatCol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.start_station
     *
     * @return the value of ticket.start_station
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public String getStartStation() {
        return startStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.start_station
     *
     * @param startStation the value for ticket.start_station
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setStartStation(String startStation) {
        this.startStation = startStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.start_time
     *
     * @return the value of ticket.start_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.start_time
     *
     * @param startTime the value for ticket.start_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.end_station
     *
     * @return the value of ticket.end_station
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public String getEndStation() {
        return endStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.end_station
     *
     * @param endStation the value for ticket.end_station
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setEndStation(String endStation) {
        this.endStation = endStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.end_time
     *
     * @return the value of ticket.end_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.end_time
     *
     * @param endTime the value for ticket.end_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.seat_type
     *
     * @return the value of ticket.seat_type
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public String getSeatType() {
        return seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.seat_type
     *
     * @param seatType the value for ticket.seat_type
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setSeatType(String seatType) {
        this.seatType = seatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.create_time
     *
     * @return the value of ticket.create_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.create_time
     *
     * @param createTime the value for ticket.create_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.update_time
     *
     * @return the value of ticket.update_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.update_time
     *
     * @param updateTime the value for ticket.update_time
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket
     *
     * @mbg.generated Fri Sep 29 18:30:25 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", passengerId=").append(passengerId);
        sb.append(", passengerName=").append(passengerName);
        sb.append(", trainDate=").append(trainDate);
        sb.append(", trainCode=").append(trainCode);
        sb.append(", carriageIndex=").append(carriageIndex);
        sb.append(", seatRow=").append(seatRow);
        sb.append(", seatCol=").append(seatCol);
        sb.append(", startStation=").append(startStation);
        sb.append(", startTime=").append(startTime);
        sb.append(", endStation=").append(endStation);
        sb.append(", endTime=").append(endTime);
        sb.append(", seatType=").append(seatType);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}